- name: Setup Mac
  vars_files:
    - ./config.yml
  vars:
    architecture: {ansible_architecture}
  hosts: all
  roles:
    #    - homebrew
    #    - npm
    #    - mas
    #    - zsh
    #    - tmux
    #    - vim
    - dock
