- name: See if Dock item exists.
  ansible.builtin.command: "dockutil --find '{{ item.name | default(item) }}'"
  register: dockitem_exists
  failed_when: >
    "No such file or directory" in dockitem_exists.stdout
    or "command not found" in dockitem_exists.stdout

- debug: msg={{dockitem_exists}}
- name: Add to dock
  ansible.builtin.command: dockutil --add '/Applications/{{item.name | default(item)}}.app'
  when: dockitem_exists.rc >0

