- name: Add Dock Items
  ansible.builtin.include_tasks: add.yml
  loop: "{{ macos_dock.add }}"


- name: Remove Dock Items
  ansible.builtin.include_tasks: remove.yml
  loop: "{{ macos_dock.remove }}"

- name: Move positions
  ansible.builtin.include_tasks: position.yml
  when:
    - item.position is defined
    - item.position > 0
  loop: "{{macos_dock.add}}"
