- name: Check Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew

- name: Homebrew Taps
  homebrew_tap:
    name: "{{item.name | default(item)}}"
    state: "{{item.state | default('present')}}"
    url: "{{item.url | default(omit)}}"
  ignore_errors: yes
  with_items: "{{taps}}"

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: not brew.stat.exists
  

- name: Install Homebrew Packages
  homebrew:
    name: "{{item.name | default(item)}}"
    state: "{{item.state | default('present')}}"
  ignore_errors: yes
  with_items: "{{brews}}"

- name: HomeBrew Casks
  homebrew_cask:
    name: "{{item.name | default(item)}}"
    state: "{{item.state | default('present')}}"
  ignore_errors: yes
  with_items: "{{casks}}"
