- name: Check Homebrew is installed
  stat: path=/usr/local/bin/brew
  register: brew

- name: Install Homebrew
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: not brew.stat.exists
  

- name: Install Homebrew Packages
  homebrew:
    name: "{{item.name | default(item)}}"
    state: "{{item.state | default('present')}}"
  with_items: "{{brews}}"


- name: Homebrew Taps
  homebrew_tap:
    name: "{{item.name | default(item)}}"
    state: "{{item.state | default('present')}}"
    url: "{{item.url | default(omit)}}"
  with_items: "{{taps}}"

## Hack for installing casks, dependency for homebrew is failing
- name: Install Cask Block
  block:
    - name: Install Cask
      shell:  brew install --cask "{{item}}"
      loop: "{{casks}}"
      register: cask
  rescue:
    - name: Print when errors
      debug:
        msg: "rescued already installed"

