- name: Vim Package Manger
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
 
- name: Vim Init
  template:
    src: "templates/{{item.name}}"
    dest: "./test/{{item.output}}"
    owner: "{{lookup('env', 'USER')}}"
    force: yes
  notify:
    - Install Vim Plugins
  loop:
    - name: init.vim.j2
      output: init.vim

